# Generated by Django 2.2.1 on 2019-05-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dog_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/%Y/%m/%D/'),
        ),
    ]
