# Generated by Django 2.2.1 on 2019-05-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190514_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(default='dog_default.jpg', upload_to='dogs/%Y/%m/%D/'),
        ),
    ]
