# Generated by Django 2.2.1 on 2019-05-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190514_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(default='default.jpg', upload_to='dogs/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100)),
                ('article_content', models.TextField(default='This article has no content yet..')),
                ('article_ct_date', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(to='app.Tag')),
            ],
        ),
    ]
