# Generated by Django 2.2.1 on 2019-05-15 03:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190514_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mce_content', tinymce.models.HTMLField()),
            ],
        ),
    ]
