# Generated by Django 2.2.1 on 2019-05-21 00:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mce',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
