# Generated by Django 2.2.1 on 2019-05-27 23:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190521_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant_full_name', models.CharField(max_length=255)),
                ('occupant_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('occupant_full_name',),
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_no', models.CharField(default=uuid.uuid4, max_length=255)),
                ('desk_level', models.IntegerField()),
                ('desk_build_date', models.DateTimeField(auto_now_add=True)),
                ('desk_info_modified', models.DateTimeField(auto_now=True)),
                ('desk_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desk_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desk_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desk_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desk_occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Occupant')),
            ],
            options={
                'ordering': ('desk_no',),
            },
        ),
    ]
